# Generated by Django 5.1.5 on 2025-02-04 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='compnay_id',
            new_name='company_id',
        ),
    ]
